### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by tillea** [ferdymercury/amide#17]
Hi,
to create an up to date Debian package we rely on properly set tags.  A user reported that you have released version 1.0.6 which is not visible as tag.  It would be really helpful if you would use tags for any release.
Thanks a lot, Andreas.

**Comment by ferdymercury** [comment]
Hi Andreas, this is an untested 'fork' of the official repository on sourceforge http://amide.sourceforge.net/ https://sourceforge.net/projects/amide/

Its owner A Loening released a new version 1.0.6 one week ago, but I think it didn't involve code changes, just the Windows installer. The sourceforge repository is rather 'non-maintained', which is why I forked it into GitHub to fix some issues.

That being said, if you want me to add tags at some places in the code, I can do that, but it should be clear that they do not match with the official release tags.

**Comment by ferdymercury** [comment]
@enlf-dev can you confirm?

**Comment by enlf-dev** [comment]
That is correct. The latest repo version from here was cloned. No code changes were needed to compile properly on MSYS2.

We send and updated 64bit and 32bit installer, including a howto for both.
